Full functionality of resource quiz implemented
redacademy/nova-winter-2018 pull request #139
Opened 2018-03-21 21:55 UTC by michaelujkim

2018-03-21 23:05 UTC, siddharthparmar7 requested changes
Thank you, Mike!

Please make the requested changes and I will approve this pull request.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/navigation/NavigationHelper.js
>  // https://red-adp.herokuapp.com/lesson/02-navigation-and-dependencies/
Please remove this comment.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/redux/modules/quiz.js
> +
Remove space

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/redux/modules/quiz.js
> +
Please remove space and put a comment on top of action creators not directly under the actions. It creates confusion.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTest/ProjectResourceTest.js
> +      cardIndex: 0
Please use the redux store. Do not use component state and the redux store, both.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTest/ProjectResourceTest.js
> +      <View style={styles.cardContainer}>
Please create a component for this JSX.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTest/ProjectResourceTest.js
> +    if (this.props.questions) {
Please use the ternary operator if you are comfortable with it.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTest/ProjectResourceTest.js
> +              overlayLabels={{
Please put these styles into the styles.js file.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTest/ProjectResourceTest.js
> +}
Can you please add prop type validation? since you are using props.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTest/ProjectResourceTestContainer.js
> +ProjectResourceTestContainer.propTypes = {
Please add validation for the other props that you are using.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTestResults/ProjectResourceTestResultsContainer.js
> +  componentDidMount() {}
remove this if you are not using it.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTestResults/ProjectResourceTestResultsContainer.js
Please add the prop types for the props that you are using.

2018-03-21 23:05 UTC, siddharthparmar7 commented on js/scenes/UserAccountConfirm/UserAccountConfirmContainer.js
>  const { black, mediumGrey, nearBlack, green, red } = colors;
Please remove the colors that you are not using.

2018-03-22 17:19 UTC, michaelujkim commented
Hi, all changes made, hope it's good!

2018-03-22 18:16 UTC, siddharthparmar7 requested changes
Great job, Mike! 

Please make the change and I will be able to approve this pull request.

Thank you!

2018-03-22 18:16 UTC, siddharthparmar7 commented on js/scenes/ProjectResourceTest/ProjectResourceTest.js
> +  scorebank: []
if you are doing proptype .isRequired, you do not have to make a default prop for it. Please remove scorebank: [].

2018-03-22 18:29 UTC, michaelujkim commented
Thanks, removed the isrequired.

2018-03-22 22:29 UTC, siddharthparmar7 approved these changes
thank you!

2018-03-22 22:29 UTC, merged