css for project Confirm page done
redacademy/nova-winter-2018 pull request #87
Opened 2018-03-16 18:42 UTC by michaelujkim

2018-03-16 23:48 UTC, siddharthparmar7 requested changes
Thank you, Mike.

s/scenes/ProjectConfirm/ProjectConfirm.js -> imports first and then consts. 

remove comments from js/scenes/ProjectConfirm/ProjectConfirmContainer.js file and remove import for propTypes in the same file.

nearBlack is not a good name, try to rename it with something meaningful. You are not using all the colors you destructured. 

Please, remove comment from serProfileConfirmContainer.js file regarding propTypes.

Thank you!

2018-03-18 17:38 UTC, michaelujkim commented
Thanks,
 I couldn't think of a better name than nearblack, as there is a color that is only slightly lighter than black. I didn't think dark grey was good because we have another color that is dark grey for some text boxes.

2018-03-19 16:50 UTC, siddharthparmar7 requested changes
Thank you!

2018-03-19 16:50 UTC, siddharthparmar7 commented on js/scenes/ProjectConfirm/styles.js
> +const { black, mediumGrey, nearBlack, green, red, white } = colors;
remove the colors that you are not using. How about calling it "tintBlack" instead of "nearBlack"?

2018-03-19 16:50 UTC, siddharthparmar7 commented on js/scenes/UserProfileConfirm/UserProfileConfirmContainer.js
>  // https://projects.invisionapp.com/share/GRFWI99HZKW#/screens/279885489
Please remove this comment.

2018-03-19 16:50 UTC, siddharthparmar7 commented on js/scenes/UserProfileConfirm/UserProfileConfirmContainer.js
>  class UserProfileConfirmContainer extends Component {
Please remove a comment from line 19.

2018-03-19 18:21 UTC, closed without merging